### ISSUE TITLE
area of unions gives only the sum of the areas of the individual polygons

### ISSUE THREAD

**Issue by Arrondissement5etDemi** [mancellin/PolygonArea.jl#1]
For example:
`r1 = rectangle(0.0, 0.0, 2.0, 2.0)
`
`r3 = rectangle(1.5, 1.5, 2.5, 2.5)`
`area(r1 ∪ r3)`
This gives 5.0 instead of the correct answer 4.75.

**Comment by mancellin** [comment]
Thank you for your interest!

Short answer: you have to call `disjoint` to make it work. Sorry for not documenting that.
```
r1 = rectangle(0.0, 0.0, 2.0, 2.0)
r3 = rectangle(1.5, 1.5, 2.5, 2.5)
area(PolygonArea.disjoint(r1 ∪ r3))
# 4.75
```

Long answer: I had some performance issues with unions of polygons because the code only really encodes convex polygons. Non-convex polygons are implemented as unions of convex ones. But in general it is not cheap to recut a union of overlapping polygons such as your `r1 ∪ r3` into a union of non-overlapping convex polygons. So it is not done automatically and you have to ask for it manually with `disjoint`. I'm not completely satisfied with this design and any suggestion for improvement is welcome.

**Comment by Arrondissement5etDemi** [comment]
Thanks! Will think about the issue of non-convex polygons. :)
